name: Variables
hosts: localhost
connection: local
vars:
  URL: www.google.com
tasks:
  - name: Print Variables
    ansible.builtin.debug:
      msg: URL = {{ URL }}

# Ansible access the variables by two flower brackets.