- name: Variable Types
  hosts: localhost
  connection: local
  vars:
    crickter_name: dhoni
    stats: 10000
    crickter: 'true'

  tasks:
    - name: Print
      ansible-builtin.debug:
       msg: crickter - {{ dhoni }} , stats - {{ 10000 }}
      when: crickter is true

