- name: Demo on Loops
  hosts: localhost
  connection: local
  vars:
    fruits:
      - orange
      - apple

  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: fruit name - "{{ item }}"
      loops: " {{ fruits }}"

  tasks:
    - name: Print Fruits Local Values
      ansible.builtin.debug:
        msg: fruit name - "{{ item }}"
      loops:
        - bananas
        - kiwi

  tasks:
    - name: Print Fruits name quantity
      ansible.builtin.debug:
        msg: Crickter name - {{ item.name }} , {{ item.quantity }}
      loops:
        - { name: "orange", quantity: 100 }
        - { name: "apple", quantity: 200 }

